"""
Offline IP Reputation / Threat Intelligence module.

Downloads free public blocklists once a day and stores them locally.
No API key, no account — all data stays on your server.

Default sources
---------------
  • Spamhaus DROP   — hijacked / rogue networks
  • Spamhaus EDROP  — extended DROP (delegated)
  • Firehol Level 1 — aggregated from ~30 verified sources
  • CINS Army       — bad guys identified by Shadowserver/CINS
  • Emerging Threats — IPs that actively attack infrastructure

Usage
-----
    ti = ThreatIntel(enabled=True, db_path="reports/threat_intel.txt")
    ti.update()                      # download all sources → saves to db_path
    src = ti.is_known_bad("1.2.3.4")  # returns source label or None
"""

import ipaddress
import logging
import os
import threading
import time
import urllib.request
from typing import Dict, List, Optional, Tuple

log = logging.getLogger("brute-force-detector.threat_intel")

# ---------------------------------------------------------------------------
# Free, public threat intel feeds — no key, no registration required
# ---------------------------------------------------------------------------
DEFAULT_SOURCES: Dict[str, str] = {
    "spamhaus_drop":    "https://www.spamhaus.org/drop/drop.txt",
    "spamhaus_edrop":   "https://www.spamhaus.org/drop/edrop.txt",
    "firehol_l1":       "https://iplists.firehol.org/files/firehol_level1.netset",
    "cins_army":        "https://cinsscore.com/list/ci-badguys.txt",
    "emerging_threats": "https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt",
}

_DB_HEADER = (
    "# BRUTUS threat intelligence database\n"
    "# Auto-generated by --update-threat-db  —  do not edit manually\n"
    "# Format: <ip_or_cidr>\\t<source_label>\n"
)

_HTTP_TIMEOUT = 20  # seconds per download request
_USER_AGENT   = "BRUTUS-threat-intel/1.2 (https://github.com/sp0ko/BRUTUS)"


# ---------------------------------------------------------------------------

class ThreatIntel:
    """
    Offline IP reputation checker backed by local flat-file database.

    Workflow
    --------
    1. Run once with ``--update-threat-db`` to populate ``db_path``.
    2. On subsequent starts the DB is loaded in ~50 ms.
    3. Optionally set ``auto_update: true`` in config for daily refresh.

    Thread-safe: ``is_known_bad()`` can be called from any thread.
    """

    def __init__(
        self,
        enabled: bool,
        db_path: str = "reports/threat_intel.txt",
        sources: Optional[Dict[str, str]] = None,
        auto_update: bool = False,
        update_interval: int = 86400,
        timeout: int = _HTTP_TIMEOUT,
    ) -> None:
        self.enabled         = enabled
        self.db_path         = db_path
        self.sources         = sources if sources is not None else DEFAULT_SOURCES
        self.auto_update     = auto_update
        self.update_interval = update_interval
        self.timeout         = timeout

        # Internal state — protected by _lock
        self._lock: threading.RLock = threading.RLock()
        self._exact:    Dict[str, str]                         = {}  # ip_str → source
        self._networks: List[Tuple[ipaddress._BaseNetwork, str]] = []  # (network, source)
        self._count: int = 0

        if enabled:
            self._load()
            if auto_update:
                self._start_scheduler()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def is_known_bad(self, ip: str) -> Optional[str]:
        """
        Return the source label if *ip* is in any loaded blocklist, else None.
        O(1) for exact IPs, O(n_cidrs) for CIDR ranges.
        """
        if not self.enabled or self._count == 0:
            return None
        try:
            addr = ipaddress.ip_address(ip)
        except ValueError:
            return None

        with self._lock:
            # Fast path — exact IP
            src = self._exact.get(ip)
            if src:
                return src
            # CIDR containment check
            for net, src in self._networks:
                if addr in net:
                    return src
        return None

    def update(self) -> int:
        """
        Download all configured sources, merge, deduplicate and save to
        ``db_path``.  Returns the total number of entries written.
        """
        all_entries: List[Tuple[str, str]] = []  # (cidr_or_ip, source)

        for name, url in self.sources.items():
            try:
                log.info("Threat intel: downloading %-20s ← %s", name, url)
                req = urllib.request.Request(
                    url, headers={"User-Agent": _USER_AGENT}
                )
                with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                    raw = resp.read().decode("utf-8", errors="replace")
                entries = _parse_feed(raw)
                log.info("  %-22s %d entries", name + ":", len(entries))
                all_entries.extend((e, name) for e in entries)
            except Exception as exc:
                log.warning("Threat intel: failed to download %s: %s", name, exc)

        if not all_entries:
            log.warning("Threat intel: nothing downloaded — keeping existing DB")
            return self._count

        # Deduplicate (keep first source for duplicates)
        seen: Dict[str, str] = {}
        for cidr, src in all_entries:
            if cidr not in seen:
                seen[cidr] = src

        os.makedirs(os.path.dirname(os.path.abspath(self.db_path)), exist_ok=True)
        with open(self.db_path, "w", encoding="utf-8") as f:
            f.write(_DB_HEADER)
            for cidr, src in sorted(seen.items()):
                f.write(f"{cidr}\t{src}\n")

        total = len(seen)
        log.info("Threat intel: DB saved — %d unique entries → %s", total, self.db_path)
        self._load()
        return total

    def count(self) -> int:
        """Number of entries currently loaded in memory."""
        return self._count

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _load(self) -> int:
        """Load DB from ``db_path``.  Returns entry count."""
        if not os.path.isfile(self.db_path):
            log.debug(
                "Threat intel DB not found at %s — run --update-threat-db to download",
                self.db_path,
            )
            return 0

        exact:    Dict[str, str]                         = {}
        networks: List[Tuple[ipaddress._BaseNetwork, str]] = []

        with open(self.db_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t", 1)
                cidr = parts[0].strip()
                src  = parts[1].strip() if len(parts) > 1 else "threat_intel"
                try:
                    net = ipaddress.ip_network(cidr, strict=False)
                except ValueError:
                    continue
                # Exact IP (/32 or /128) → exact dict for O(1) lookup
                if net.prefixlen == net.max_prefixlen:
                    exact[str(net.network_address)] = src
                else:
                    networks.append((net, src))

        with self._lock:
            self._exact    = exact
            self._networks = networks
            self._count    = len(exact) + len(networks)

        log.info(
            "Threat intel loaded: %d entries  (%d exact IPs, %d CIDRs)  [%s]",
            self._count, len(exact), len(networks), self.db_path,
        )
        return self._count

    def _start_scheduler(self) -> None:
        def _loop() -> None:
            while True:
                time.sleep(self.update_interval)
                try:
                    self.update()
                except Exception as exc:
                    log.error("Threat intel auto-update failed: %s", exc)

        threading.Thread(
            target=_loop, daemon=True, name="threat-intel-updater"
        ).start()
        log.debug(
            "Threat intel auto-update scheduler started (interval=%ds)",
            self.update_interval,
        )


# ---------------------------------------------------------------------------
# Feed parser
# ---------------------------------------------------------------------------

def _parse_feed(raw: str) -> List[str]:
    """
    Parse a threat intel feed in any of the common formats:
      • Lines starting with ``#`` or ``;`` → comments / ignored
      • Spamhaus DROP: ``ip/cidr ; SBLxxx``
      • Firehol netset: bare CIDRs
      • CINS / ET:  bare IPs
    Returns a list of valid IP / CIDR strings.
    """
    results: List[str] = []
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        # First whitespace-delimited token, strip trailing ; or ,
        token = line.split()[0].rstrip(";,")
        if not token or token.startswith("#"):
            continue
        try:
            ipaddress.ip_network(token, strict=False)
            results.append(token)
        except ValueError:
            pass
    return results
